/*
 * This file is part of Mapdroid.
 * Copyright 2009 Ted Percival <ted@tedp.id.au>.
 *
 * Mapdroid is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * Mapdroid is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Mapdroid. If not, see <http://www.gnu.org/licenses/>.
 */
package au.id.tedp.mapdroid;

import android.graphics.Bitmap;
import java.lang.String;

class Tile {
    private Bitmap bmp; // may be null
    private int zoomLevel;
    private int x, y;
    // When the tile was generated by scaling an existing tile up or down,
    // it is marked "dirty" so that the tile at the correct scale can be
    // downloaded and replace it.
    private boolean dirty;
    private String url;

    public Tile(String url, int zoom, int x, int y) {
        this.url = url;
        this.zoomLevel = zoom;
        this.x = x;
        this.y = y;
    }

    // XXX: Does anyone even use this constructor anymore?
    public Tile(Bitmap src, int zoom, int x, int y) {
        bmp = src;
        zoomLevel = zoom;
        this.x = x;
        this.y = y;
    }

    public void setBitmap(Bitmap newbmp) {
        bmp = newbmp;
    }

    public Bitmap getBitmap() {
        return bmp;
    }

    public int getZoom() {
        return zoomLevel;
    }

    public int getXTileNumber() {
        return x;
    }

    public int getYTileNumber() {
        return y;
    }

    public String getUrl() {
        return url;
    }
}

/* vim: set ts=4 sw=4 et :*/
